[placement]
mode = "smart"
name = "cf-image-proxy"
type = "javascript"
webpack_config = "webpack.config.js"
account_id = "9fd45848e3091b81b9da211a233c1c21"
workers_dev = true

[env.production]
zone_id = "cf-image-proxy.pages.dev"
route = "a46b0251.cf-image-proxy.pages.dev"
